default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'] || 'kotobano_tane_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'kotobano_tane_test' %>

production:
  <<: *default
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
  host: <%= ENV['PROD_DB_HOST'] %>
  database: <%= ENV['PROD_DB_NAME'] %>

cache:
  <<: *default
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
  host: <%= ENV['PROD_DB_HOST'] %>
  database: <%= ENV['PROD_CACHE_DB_NAME'] || 'kotobano_tane_cache_production' %>
