jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TEST_DB_USERNAME: postgres
      TEST_DB_PASSWORD: ""
      TEST_DB_HOST: 127.0.0.1
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Create and migrate database
        run: |
          bin/rails db:create
          bin/rails db:migrate
      - name: Run tests
        run: bin/rails test
